# Generated by Django 2.1.7 on 2019-03-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
