# Generated by Django 2.1.7 on 2019-03-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190329_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'author')},
        ),
    ]
