# Generated by Django 2.1.7 on 2019-03-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190329_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='description_html',
        ),
        migrations.AddField(
            model_name='post',
            name='description_text',
            field=models.TextField(default='', max_length=8192),
        ),
    ]
